# -*- coding: utf-8 -*-
"""Proyek Analisis Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NowOBNJ7OvPTe4DFPphpGedq6LLNPjxT

# Proyek Analisis Data: [Input Nama Dataset]

---


- **Nama:** Daffa Setyo Irshandy
- **Email:** daffasetyo16@gmail.com
- **ID Dicoding:** daffa_setyo_irshandy

## Menentukan Pertanyaan Bisnis

- Kota mana yang melakukan transaksi pembelian terbanyak dan sedikit ?

- Berapa lama durasi pengiriman kepada customer setelah melakukan transaksi?

- Pada kategori produk apa yang memiliki penjualan tertinggi?

## Import Semua Packages/Library yang Digunakan
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""## Data Wrangling

### Gathering Data
"""

customers_df = pd.read_csv('customers_dataset.csv')
customers_df.head()

sellers_df = pd.read_csv('sellers_dataset.csv')
sellers_df.head()

products_df = pd.read_csv('products_dataset.csv')
products_df.head()

orders_df = pd.read_csv('orders_dataset.csv')
orders_df.head()

"""### Assessing Data"""

customers_df.info()
customers_df.describe()
customers_df.isna().sum()
print("Jumlah duplikasi: ", customers_df.duplicated().sum())
print("Data kosong: ", customers_df.isnull().sum())

sellers_df.info()
sellers_df.describe()
sellers_df.isna().sum()
print("Jumlah duplikasi: ", sellers_df.duplicated().sum())
print("Data kosong: ", sellers_df.isnull().sum())

products_df.info()
products_df.describe()
products_df.isna().sum()
print("Jumlah duplikasi: ", products_df.duplicated().sum())
print("Data kosong: ", products_df.isnull().sum())

orders_df.info()
orders_df.describe()
orders_df.isna().sum()
print("Jumlah duplikasi: ", orders_df.duplicated().sum())
print("Data kosong: ", orders_df.isnull().sum())

"""### Cleaning Data"""

#membersihkan data product

products_df.fillna(value="no value", inplace=True)
products_df.isnull().sum()
products_df.info()

# membersihkan data orders
# data waktu masih dalam bentuk object

waktu = ['order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']
for column in waktu:
    orders_df[column] = pd.to_datetime(orders_df[column])

orders_df.fillna(value="2018-05-08 23:38:46", inplace=True)
orders_df.info()

"""## Exploratory Data Analysis (EDA)

### Explore data pembeli terbanyak dan sedikit berdasarkan kota
"""

customers_df.describe(include="all")

customers_df.groupby(by="customer_state").customer_id.nunique().sort_values(ascending=False)

"""## Visualization & Explanatory Analysis

### Pertanyaan 1:
"""

customer_city = customers_df.groupby(by="customer_state").customer_id.nunique().sort_values(ascending=False)

# Membuat visualisasi bar chart
plt.figure(figsize=(10, 5))
customer_city.plot(kind='bar')
plt.title('Jumlah Pembeli Berdasarkan state')
plt.xlabel('state')
plt.ylabel('Jumlah Pembeli')
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

"""### Pertanyaan 2:"""

orders_df['order_purchase_timestamp'] = pd.to_datetime(orders_df['order_purchase_timestamp'])
orders_df['order_delivered_customer_date'] = pd.to_datetime(orders_df['order_delivered_customer_date'])
orders_df['delivery_time'] = orders_df['order_delivered_customer_date'] - orders_df['order_purchase_timestamp']

orders_df['delivery_time_days'] = orders_df['delivery_time'].dt.days
print(orders_df[['order_purchase_timestamp', 'order_delivered_customer_date', 'delivery_time_days']])

orders_df.describe(include="all")

average_delivery_time = orders_df['delivery_time_days'].mean()

# Menemukan waktu pengiriman tercepat
fastest_delivery_time = orders_df['delivery_time_days'].min()

# Menemukan waktu pengiriman terlama
slowest_delivery_time = orders_df['delivery_time_days'].max()

# Membuat visualisasi bar chart
plt.figure(figsize=(8, 6))
plt.bar(['Rata-rata', 'Tercepat', 'Terlama'], [average_delivery_time, fastest_delivery_time, slowest_delivery_time])
plt.title('Waktu Pengiriman')
plt.xlabel('Jenis Waktu Pengiriman')
plt.ylabel('Hari')
plt.show()

print("Rata-rata waktu pengiriman: ", average_delivery_time, " hari")
print("Waktu pengiriman tercepat: ", fastest_delivery_time, " hari")
print("Waktu pengiriman terlama: ", slowest_delivery_time, " hari")

"""## Conclusion

- dapat disimpulkan bahwa pembeli dengan minat tertinggi pada State SP (San Paulo). dan pembeli dengan minat paling rendah berada di state RR (Roraima)
- dapat disimpulkan bahwa rata-rata waktu pengiriman sebesar 17 hari dengan nilai maksimum sebesar 611 hari dan nilai minimum sebesar 0 hari.
"""